In [30]:
from sklearn.cluster import KMeans
from skimage.io import imread, imsave
from skimage.color import rgb2gray
from skimage.transform import resize
import os
import numpy as np
from PIL import Image
from numpy import asarray

ls11=[]
ls_name11=[]
# Set the number of clusters
num_clusters = 2

# Set the input and output directories
input_dir = 'C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_data'
output_dir = 'C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_output'

# Get a list of all image files in the input directory
image_files = os.listdir(input_dir)

# Loop over each image and perform clustering
for image_file in image_files:
    # Load the image
    
    
    img=Image.open(input_dir+'\\'+image_file)
    imgGray=img.convert('L')
    
    numpydata = asarray(imgGray)
    #imgGray.show()
    
   # image = imread(os.path.join(input_dir, image_file))
    #print(image.shape, image_file)
    # Preprocess the image

    
    #image_gray = rgb2gray(image)
    image_small = resize(numpydata, (100, 100))
    image_flat = image_small.flatten()#.reshape(-1, 1)
    
    ls11.append(image_flat)
    ls_name11.append(image_file)
    

#     # Perform K-means clustering
#     kmeans = KMeans(n_cluster
s=num_clusters)
#     kmeans.fit(image_flat)
    
#     # Label the clusters
#     labels = np.arange(num_clusters)
    
#     # Assign labels to the pixels
#     cluster_labels = kmeans.predict(image_flat)
#     classified = labels[cluster_labels].reshape(image_small.shape)
    
#     # Save the classified image
#     imsave(os.path.join(output_dir, image_file), classified)


In [8]:
ls

[array([[0.93211845],
        [0.93211845],
        [0.93211845],
        ...,
        [0.91032936],
        [0.91032947],
        [0.91032463]]),
 array([[0.32811572],
        [0.2803458 ],
        [0.31267397],
        ...,
        [0.59375261],
        [0.57039305],
        [0.7391259 ]]),
 array([[0.58444362],
        [0.46524537],
        [0.34333986],
        ...,
        [0.80312522],
        [0.80704679],
        [0.75214483]]),
 array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([[0.39883606],
        [0.2524801 ],
        [0.08252586],
        ...,
        [0.83407859],
        [0.74707577],
        [0.5179344 ]]),
 array([[1.        ],
        [0.99607843],
        [0.98823529],
        ...,
        [1.        ],
        [0.99607843],
        [0.98823529]]),
 array([[0.13601013],
        [0.31716808],
        [0.1640834 ],
        ...,
        [0.91118204],
        [0.77341671],
        [0.56735651]]),
 array([[1.],
     

In [10]:
from PIL import Image

In [13]:
img=Image.open('C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_data\\71xkI-PIE5L._SL1500_.jpg')
imgGray=img.convert('L')
imgGray.show()

In [16]:
image_files

['0817-web-week-basically-smashed-cucumbers02.jpg',
 '1200px-Australia_Cucumbers_for_sale_at_store.jpg',
 '1657897212314.jpeg',
 '1781-done_1024x1024.jpg',
 '20200721_175412.jpg',
 '220px-Cucumber_BNC.jpg',
 '283006_2200-732x549.jpg',
 '30000456_10-fresho-cucumber-white.jpg',
 '360_F_324224284_KEgkz9bGAROme3X5j9k3ddwiHm3BE2IO.jpg',
 '518dyGWBYUL._SX466_.jpg',
 '71xkI-PIE5L._SL1500_.jpg',
 '7e355a4b3ad12ed0d91c734d6022f097.jpg',
 '7p2jtu6g_cucumber-seeds_625x300_10_July_19.jpg',
 'AN88-Cucumbers-732x549-thumb-1-732x549.jpg',
 'apple_1.jpg',
 'apple_10.jpg',
 'apple_11.jpg',
 'apple_12.jpg',
 'apple_13.jpg',
 'apple_14.jpg',
 'apple_15.jpg',
 'apple_16.jpg',
 'apple_17.jpg',
 'apple_18.jpg',
 'apple_19.jpg',
 'apple_2.jpg',
 'apple_20.jpg',
 'apple_21.jpg',
 'apple_22.jpg',
 'apple_23.jpg',
 'apple_24.jpg',
 'apple_25.jpg',
 'apple_26.jpg',
 'apple_27.jpg',
 'apple_28.jpg',
 'apple_29.jpg',
 'apple_3.jpg',
 'apple_30.jpg',
 'apple_31.jpg',
 'apple_32.jpg',
 'apple_33.jpg',
 'apple_35.jpg

In [24]:
ls1

[array([[0.93211845],
        [0.93230248],
        [0.93220235],
        ...,
        [0.91408785],
        [0.91319875],
        [0.9103292 ]]),
 array([[0.29860753],
        [0.31387207],
        [0.26733766],
        ...,
        [0.33080446],
        [0.55321853],
        [0.59658688]]),
 array([[0.48682028],
        [0.64970542],
        [0.67152347],
        ...,
        [0.74474898],
        [0.76292483],
        [0.79920365]]),
 array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([[0.27695698],
        [0.4126116 ],
        [0.49455778],
        ...,
        [0.69537476],
        [0.65978354],
        [0.74688108]]),
 array([[0.99607843],
        [0.99607843],
        [0.99607843],
        ...,
        [0.99607843],
        [0.99607843],
        [0.99607843]]),
 array([[0.24619686],
        [0.23027183],
        [0.21027288],
        ...,
        [0.77155218],
        [0.77911615],
        [0.79149132]]),
 array([[1.],
     

In [31]:
import pandas as pd
#ls2=ls1.to_array()
#ls2 = ls2[:, :, 0]

df=pd.DataFrame(ls11)
df.head()

0         1         2         3         4         5         6     \
0  0.932118  0.932302  0.932202  0.931356  0.931537  0.932309  0.932373   
1  0.298608  0.313872  0.267338  0.281088  0.287940  0.292312  0.281800   
2  0.486820  0.649705  0.671523  0.644334  0.468854  0.395068  0.394911   
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4  0.276957  0.412612  0.494558  0.524397  0.503037  0.471373  0.607195   

       7         8         9     ...      9990      9991      9992      9993  \
0  0.933370  0.933103  0.933908  ...  0.906737  0.912045  0.914293  0.916048   
1  0.302983  0.302830  0.306353  ...  0.433041  0.200505  0.118312  0.129240   
2  0.409103  0.423186  0.426656  ...  0.786234  0.789650  0.784964  0.777543   
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
4  0.559982  0.534465  0.365381  ...  0.644443  0.776503  0.857911  0.815997   

       9994      9995      9996      9997      9998      9999  
0  0.916082  0.915896  0.915034  0.914088  0.913199  0.910329  
1  0.193354  0.273368  0.327018  0.330804  0.553219  0.596587  
2  0.777018  0.766444  0.753706  0.744749  0.762925  0.799204  
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
4  0.580549  0.759799  0.822669  0.695375  0.659784  0.746881  

[5 rows x 10000 columns]

In [32]:
df

0         1         2         3         4         5         6     \
0    0.932118  0.932302  0.932202  0.931356  0.931537  0.932309  0.932373   
1    0.298608  0.313872  0.267338  0.281088  0.287940  0.292312  0.281800   
2    0.486820  0.649705  0.671523  0.644334  0.468854  0.395068  0.394911   
3    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4    0.276957  0.412612  0.494558  0.524397  0.503037  0.471373  0.607195   
..        ...       ...       ...       ...       ...       ...       ...   
258  0.996190  0.996087  0.996405  0.999201  0.999995  1.000000  1.000000   
259  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
260  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
261  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
262  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

         7         8         9     ...      9990      9991      9992  \
0    0.933370  0.933103  0.933908  ...  0.906737  0.912045  0.914293   
1    0.302983  0.302830  0.306353  ...  0.433041  0.200505  0.118312   
2    0.409103  0.423186  0.426656  ...  0.786234  0.789650  0.784964   
3    1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
4    0.559982  0.534465  0.365381  ...  0.644443  0.776503  0.857911   
..        ...       ...       ...  ...       ...       ...       ...   
258  1.000000  1.000000  1.000000  ...  0.964987  0.962433  0.960845   
259  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
260  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
261  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
262  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   

         9993      9994      9995      9996      9997      9998      9999  
0    0.916048  0.916082  0.915896  0.915034  0.914088  0.913199  0.910329  
1    0.129240  0.193354  0.273368  0.327018  0.330804  0.553219  0.596587  
2    0.777543  0.777018  0.766444  0.753706  0.744749  0.762925  0.799204  
3    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
4    0.815997  0.580549  0.759799  0.822669  0.695375  0.659784  0.746881  
..        ...       ...       ...       ...       ...       ...       ...  
258  0.960885  0.963888  0.982713  0.988136  0.988176  0.986144  0.984502  
259  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
260  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
261  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
262  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  

[263 rows x 10000 columns]

In [34]:
from sklearn.cluster import MiniBatchKMeans
from sklearn import metrics

In [35]:
kmeans_model=KMeans(n_clusters=2,max_iter=1000).fit(df)

C:\Users\Kreena\anaconda3\envs\deep_learning\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Kreena\anaconda3\envs\deep_learning\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(


In [36]:
kmeans_centroid=kmeans_model.cluster_centers_
kmeans_centroid

array([[0.97040192, 0.97183392, 0.9729162 , ..., 0.95298842, 0.95217173,
        0.95106565],
       [0.36658046, 0.36386488, 0.36638557, ..., 0.3520884 , 0.36760862,
        0.37195774]])

In [37]:
kmeans_centroid.shape

(2, 10000)

In [38]:
np.unique(kmeans_model.labels_)

array([0, 1])

#### testing

In [39]:
test=[]
img=Image.open('C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_test\\images335.jpg')   #cucumber
imgGray=img.convert('L')

numpydata = asarray(imgGray)

image_small = resize(numpydata, (100, 100))
image_flat = image_small.flatten()

test.append(image_flat)

In [40]:
data=pd.DataFrame(test)

In [41]:
data

0     1     2     3     4     5     6     7     8     9     ...  9990  \
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   

   9991  9992  9993  9994  9995  9996  9997  9998  9999  
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  

[1 rows x 10000 columns]

In [42]:
pred_cluster=kmeans_model.predict(data)

In [43]:
pred_cluster

array([0])

In [44]:
test=[]
img=Image.open('C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_test\\banana.jpeg')   #banana
imgGray=img.convert('L')

numpydata = asarray(imgGray)

image_small = resize(numpydata, (100, 100))
image_flat = image_small.flatten()

test.append(image_flat)

In [45]:
data=pd.DataFrame(test)

In [46]:
data

0     1     2     3     4     5     6     7     8     9     ...  9990  \
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   

   9991  9992      9993      9994      9995      9996      9997      9998  \
0   1.0   1.0  0.999982  0.997027  0.992387  0.992157  0.992157  0.992157   

       9999  
0  0.992157  

[1 rows x 10000 columns]

In [47]:
pred_cluster=kmeans_model.predict(data)

In [48]:
pred_cluster

array([0])

In [64]:
test=[]
img=Image.open('C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_test\\apple.jpeg')   #apple
imgGray=img.convert('L')

numpydata = asarray(imgGray)

image_small = resize(numpydata, (100, 100))
image_flat = image_small.flatten()

test.append(image_flat)

In [65]:
data=pd.DataFrame(test)

In [66]:
data

0     1     2     3     4     5     6     7     8     9     ...  9990  \
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   

   9991  9992  9993  9994  9995  9996  9997  9998  9999  
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  

[1 rows x 10000 columns]

In [67]:
pred_cluster=kmeans_model.predict(data)

In [68]:
pred_cluster

array([0])

In [55]:
test=[]
img=Image.open('C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_test\\orange.jpeg')   #orange
imgGray=img.convert('L')

numpydata = asarray(imgGray)

image_small = resize(numpydata, (100, 100))
image_flat = image_small.flatten()

test.append(image_flat)

In [56]:
data=pd.DataFrame(test)

In [57]:
data

0         1         2         3         4         5         6     \
0  0.714736  0.732165  0.749772  0.757204  0.746563  0.743462  0.750749   

       7         8        9     ...      9990      9991      9992      9993  \
0  0.723851  0.652152  0.56731  ...  0.585967  0.607476  0.562347  0.570657   

       9994     9995      9996      9997      9998      9999  
0  0.629392  0.61565  0.592572  0.663998  0.628365  0.709838  

[1 rows x 10000 columns]

In [58]:
pred_cluster=kmeans_model.predict(data)

In [59]:
pred_cluster

array([1])

In [61]:
output_dir = 'C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_output'
imsave(os.path.join(output_dir, img))

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'JpegImageFile'

In [62]:

import os
import shutil

# Set the path of the image file
image_path = "C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_test\\orange.jpeg"

# Set the path of the destination folder
destination_folder = "C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster1"

# Check if the destination folder exists, if not, create it
if not os.path.exists(destination_folder):
    os.makedirs(destination_folder)

# Use the shutil library to copy the image file to the destination folder
shutil.copy(image_path, destination_folder)

'C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_outpu\\orange.jpeg'

In [69]:
if (pred_cluster==1):
    print('T')
else:
    print('F')

F


In [78]:
import cv2

cluster1_path="C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster1"
cluster2_path="C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster2"

for i in range(len(ls_name11)):
    im=cv2.imread(input_dir+'\\'+ls_name11[i])
    if label[i] == 0:
        cluster_path = cluster1_path
    else:
        cluster_path = cluster2_path
        
    new_path = os.path.join(cluster_path, ls_name11[i])
    cv2.imwrite(new_path, im)







# if (pred_cluster==1):
#     # Set the path of the destination folder
#     #image_path = "C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster_test\\orange.jpeg"
#     destination_folder = "C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster1"
#     shutil.copy(image_path, destination_folder)
# else:
#     destination_folder = "C:\\Users\\Kreena\\Praxis\\TERM 3\\CAPSTONE\\cluster2"
#     shutil.copy(image_path, destination_folder)
    

In [72]:
label=kmeans_model.labels_

In [70]:
ls_name11

['0817-web-week-basically-smashed-cucumbers02.jpg',
 '1200px-Australia_Cucumbers_for_sale_at_store.jpg',
 '1657897212314.jpeg',
 '1781-done_1024x1024.jpg',
 '20200721_175412.jpg',
 '220px-Cucumber_BNC.jpg',
 '283006_2200-732x549.jpg',
 '30000456_10-fresho-cucumber-white.jpg',
 '360_F_324224284_KEgkz9bGAROme3X5j9k3ddwiHm3BE2IO.jpg',
 '518dyGWBYUL._SX466_.jpg',
 '71xkI-PIE5L._SL1500_.jpg',
 '7e355a4b3ad12ed0d91c734d6022f097.jpg',
 '7p2jtu6g_cucumber-seeds_625x300_10_July_19.jpg',
 'AN88-Cucumbers-732x549-thumb-1-732x549.jpg',
 'apple_1.jpg',
 'apple_10.jpg',
 'apple_11.jpg',
 'apple_12.jpg',
 'apple_13.jpg',
 'apple_14.jpg',
 'apple_15.jpg',
 'apple_16.jpg',
 'apple_17.jpg',
 'apple_18.jpg',
 'apple_19.jpg',
 'apple_2.jpg',
 'apple_20.jpg',
 'apple_21.jpg',
 'apple_22.jpg',
 'apple_23.jpg',
 'apple_24.jpg',
 'apple_25.jpg',
 'apple_26.jpg',
 'apple_27.jpg',
 'apple_28.jpg',
 'apple_29.jpg',
 'apple_3.jpg',
 'apple_30.jpg',
 'apple_31.jpg',
 'apple_32.jpg',
 'apple_33.jpg',
 'apple_35.jpg